FROM python:3.12

WORKDIR /app

# 필요한 파일들 복사
COPY requirements.txt .
COPY app.py .
COPY .env .
COPY templates/ templates/

# 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 포트 설정
EXPOSE 5005

# 로그 디렉토리 생성
RUN mkdir -p /app/logs

# Flask 앱 실행
CMD ["python", "app.py"]
